version: '3.3'
services:
  substrave:
    container_name: substrate
    build:
      context: .
      args:
        APTPROXY_ADDR:
    restart: always
    ports:
      - "9944:9944"
      - "9615:9615"
    